src/n3b/Bundle/Kladr/Entity/MoscowStreet.php
<?php

namespace n3b\Bundle\Kladr\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 * @ORM\Table()
 */
Class MoscowStreet
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @ORM\Column
     */
    private $socr;
    /**
     * @ORM\Column
     */
    private $title;
    /**
     * @ORM\Column(type="integer")
     */
    private $zip;
    /**
     * @ORM\Column(type="bigint")
     */
    private $ocatd;
  /**
   * @ORM\Column(type="float", nullable=true)
   */
  private $lng;

  /**
   * @ORM\Column(type="float", nullable=true)
   */
  private $lat;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $mosopen_id;

    /**
     * @ORM\OneToMany(targetEntity="MoscowHouse", mappedBy="moscowStreet")
     **/
    private $houses;

  /**
     * Set id
     *
     * @param integer $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set socr
     *
     * @param string $socr
     */
    public function setSocr($socr)
    {
        $this->socr = $socr;
    }

    /**
     * Get socr
     *
     * @return string $socr
     */
    public function getSocr()
    {
        return $this->socr;
    }

    /**
     * Set title
     *
     * @param string $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * Get title
     *
     * @return string $title
     */
    public function getTitle()
    {
        return $this->title;
    }


    /**
     * Set zip
     *
     * @param integer $zip
     */
    public function setZip($zip)
    {
        $this->zip = $zip;
    }

    /**
     * Get zip
     *
     * @return integer $zip
     */
    public function getZip()
    {
        return $this->zip;
    }

    /**
     * Set ocatd
     *
     * @param bigint $ocatd
     */
    public function setOcatd($ocatd)
    {
        $this->ocatd = $ocatd;
    }

    /**
     * Get ocatd
     *
     * @return bigint $ocatd
     */
    public function getOcatd()
    {
        return $this->ocatd;
    }

    /**
     * Set parent
     *
     * @param n3b\Bundle\Kladr\Entity\KladrRegion $parent
     */
    public function setParent(\n3b\Bundle\Kladr\Entity\KladrRegion $parent)
    {
        $this->parent = $parent;
    }

    /**
     * Get parent
     *
     * @return n3b\Bundle\Kladr\Entity\KladrRegion $parent
     */
    public function getParent()
    {
        return $this->parent;
    }

  /**
   * Get lng
   *
   * @return float $lng
   */
  public function getLng()
  {
    return $this->lng;
  }

  /**
   * Get lat
   *
   * @return float $lat
   */
  public function getLat()
  {
    return $this->lat;
  }

  /**
   * Set lng
   */
  public function setLng($lng)
  {
    $this->lng = $lng;
  }

  /**
   * Set lat
   */
  public function setLat($lat)
  {
    $this->lat = $lat;
  }

    public function getMosopenId()
    {
        return $this->mosopen_id;
    }

    public function setMosopenId($mosopen_id)
    {
        $this->mosopen_id = $mosopen_id;
    }

    public function getHouses()
    {
        return $this->houses;
    }

    public function setHouses($houses)
    {
        $this->houses = $houses;
    }
}

src/n3b/Bundle/Kladr/Controller/DefaultController.php
<?php

/**
 * Created by PhpStorm.
 * User: alex
 * Date: 02.04.14
 * Time: 01:11
 */

namespace n3b\Bundle\Kladr\Controller;

use Exception;

use n3b\Bundle\Kladr\Service\Street;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

class DefaultController extends Controller
{

    /**
     * @Route("/moscow", name="kladr_moscow")
     *
     * @throws NotFoundHttpException
     * @Template()
     */

    public function moscowAction()
    {
        $ymaps_key = $this->container->getParameter('ymaps_key');
        $socr_arr = Street::SOCR;

        return [
            'ymaps_key' => $ymaps_key,
            'socr_arr' => $socr_arr,
            'map_width' => $this->getParameter('map_width'),
            'map_height' => $this->getParameter('map_height')
        ];
    }

    /**
     * @Route("/polygon/street", name="polygon_street")
     *
     * @throws NotFoundHttpException
     * @Template()
     */

    public function getPolygonStreetAction(Request $request)
    {
        $street_points = $request->request->get('street_points');
        $points_check = $request->request->get('points_check') !== 'false' ? true : false;
        $street_name = $request->request->get('street_name');
        $street_house = $request->request->get('street_house');
        $object_filter = $request->request->get('object_filter');
        $street_socr = $request->request->get('street_socr') !== 'null' ? $request->request->get('street_socr') : false;

        $pp_ar = array();
        if ($street_points && $points_check) {
            $pp_ar = json_decode($street_points);
        }

        if (count($street_socr) === 1 && !strlen($street_socr[0])) {
            $street_socr = false;
        }

        $YMaps = $this->container->get('ymaps_service');

        $streets = $YMaps->moscowFilter($street_name, $street_socr, $street_house, $pp_ar);

        return array('streets' => $streets);
    }

    /**
     * @Route("/peter", name="kladr_peter")
     *
     * @throws NotFoundHttpException
     * @Template()
     */

    public function peterAction()
    {
        $ymaps_key = $this->container->getParameter('ymaps_key');
        $socr_arr = Street::SOCR;

        return [
            'ymaps_key' => $ymaps_key,
            'socr_arr' => $socr_arr,
            'map_width' => $this->getParameter('map_width'),
            'map_height' => $this->getParameter('map_height')
        ];
    }

    /**
     * @Route("/polygon/peter_street", name="polygon_peter_street")
     *
     * @throws NotFoundHttpException
     * @Template()
     */

    public function getPolygonPeterStreetAction(Request $request)
    {
        $street_points = $request->request->get('street_points');
        $points_check = $request->request->get('points_check') !== 'false' ? true : false;
        $street_name = $request->request->get('street_name');
        $object_filter = $request->request->get('object_filter');
        $street_socr = $request->request->get('street_socr') !== 'null' ? $request->request->get('street_socr') : false;

        $pp_ar = array();
        if ($street_points && $points_check) {
            $pp_ar = json_decode($street_points);
        }

        if (count($street_socr) === 1 && !strlen($street_socr[0])) {
            $street_socr = false;
        }

        $YMaps = $this->container->get('ymaps_service');

        $streets = $YMaps->peterFilter($street_name, $street_socr, $pp_ar);

        return array('streets' => $streets);
    }

    /**
     * @Route("/", name="homepage")
     *
     * @throws NotFoundHttpException
     * @Template()
     */

    public function indexAction()
    {
        $ymaps_key = $this->container->getParameter('ymaps_key');
        // var_dump($ymaps_key);exit;

        return array('ymaps_key' => $ymaps_key);
    }
}

src/n3b/Bundle/Kladr/Resources/views/Default/getPolygonPeterStreet.html.twig
<table>
    {% for street in streets %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ street.socr }}</td>
            <td>
                <a target="_blank" class="street_item" data-lng="{{ street.lng }}" data-lat="{{ street.lat }}" href="http://yandex.ru/yandsearch?text={{ street.title }}">{{ street.title }}</a>
            </td>
        </tr>
    {%  endfor %}
</table>

src/n3b/Bundle/Kladr/Resources/views/Default/getPolygonStreet.html.twig
<table>
    {% for street in streets %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ street.socr }}</td>
            <td>
                <a target="_blank" class="street_item" data-lng="{{ street.lng }}" data-lat="{{ street.lat }}" href="http://yandex.ru/yandsearch?text={{ street.title }}">{{ street.title }}</a>
            </td>
        </tr>
    {%  endfor %}
</table>

src/n3b/Bundle/Kladr/Resources/views/Default/get_polygon_street.html.twig
<table>
    {% for street in streets %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ street.socr }}</td>
            <td>
                <a target="_blank" class="street_item" data-lng="{{ street.lng }}" data-lat="{{ street.lat }}" href="http://yandex.ru/yandsearch?text={{ street.title }}">{{ street.title }}</a>
                <a target="_blank" href="http://mosopen.ru/street/{{ street.mosopenId }}">mosopen</a>
            </td>
        </tr>
    {%  endfor %}
</table>

src/n3b/Bundle/Kladr/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   <a href="/moscow">Moscow</a>
   <a href="/piter">Piter</a>
{% endblock %}

src/n3b/Bundle/Kladr/Resources/views/Default/moscow.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% javascripts
    '@n3bKladrBundle/Resources/public/js/jquery-1.5.js'
    '@n3bKladrBundle/Resources/public/js/common.js'
    '@n3bKladrBundle/Resources/public/js/frontend.js'
    '@n3bKladrBundle/Resources/public/js/*' %}
    <script src="http://api-maps.yandex.ru/1.1/index.xml?key={{ ymaps_key }}"
            type="text/javascript"></script>
    <script type="text/javascript" src="{{ asset_url }}"></script>

{% endjavascripts %}

<script type="text/javascript">
    supplier = new Object();
    supplier.longitude  = 37.64;
    supplier.latitude   = 55.76;
    filterUrl = 'polygon/street';
</script>


<div class="b-admin-radius">
    <div class="b-admin-radius__section">
        <div class="right_column" style="float:right;width: 320px;">
            <div class="b-admin-radius__section__body b-select">
                <select name="supplier_delivery_radius[type]" id="supplier_delivery_radius_type">
                    <option value="radius">Радиус</option>
                    <option value="polygon" selected="selected">Многоугольник</option>
                    <option value="addresses">Адреса</option>
                </select>
            </div>
            <div class="street_filter">
                <input class="street_name" value="" />
                <select class="street_socr" style="height: 500px; right: 0px; position: absolute;" name="street_socr" multiple="multiple">
                    {% for socr in socr_arr %}
                        <option value="{{ socr }}">{{ socr }}</option>
                    {% endfor %}
                </select>
                <input type="checkbox" class="street_polygon" value="1">
                <input class="object_filter" value="" />
                <input class="street_house" value="" />
                <input type="hidden" class="object_res" value="" />
            </div>
            <div>
                <input type="hidden" class="polygon-points" value="" />
                <input class="show_street" name="show_street" type="button" value="Показать Улицы!" />
            </div>
            <div class="street_res">
            </div>
        </div>
        <div class="map" style="position: fixed;width:{{ map_width }};height:{{ map_height }}"></div>
    </div>
</div>
{% endblock %}
{#
{% extends 'CommonBundle:Default/admin:admin_index.html.twig' %}

{% set admin = 'admin_address_group' %}
{% set title = 'label.address_group.index' %}
{% block thead %}
    <tr>
        <th>{{ 'label.id'|trans }}</th>
        <th>{{ 'label.name'|trans }}</th>
        <th>{{ 'label.actions'|trans }}</th>
    </tr>
{% endblock %}
{% block custom_fields %}
    <td>{{ entity }}</td>
{% endblock %}#}

src/n3b/Bundle/Kladr/Resources/views/Default/peter.html.twig
{% extends 'base.html.twig' %}
{% block body %}
{% javascripts
    '@n3bKladrBundle/Resources/public/js/jquery-1.5.js'
    '@n3bKladrBundle/Resources/public/js/common.js'
    '@n3bKladrBundle/Resources/public/js/frontend.js'
    '@n3bKladrBundle/Resources/public/js/*' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    <script src="http://api-maps.yandex.ru/1.1/index.xml?key={{ ymaps_key }}"
            type="text/javascript"></script>

{% endjavascripts %}

<script type="text/javascript">
    supplier = new Object();
    supplier.longitude  = 30.37;
    supplier.latitude   = 59.93;
    filterUrl = 'polygon/peter_street';
</script>

<div class="b-admin-radius">
    <div class="b-admin-radius__section">
        <div class="right_column" style="float:right;width: 250px;">
            <div class="b-select">
                <select name="supplier_delivery_radius[type]" id="supplier_delivery_radius_type">
                    <option value="radius">Радиус</option>
                    <option value="polygon" selected="selected">Многоугольник</option>
                    <option value="addresses">Адреса</option>
                </select>
            </div>
            <div class="street_filter">
                <input class="street_name" value="" />
                <select class="street_socr" name="street_socr" multiple="multiple">
                    {% for socr in socr_arr %}
                        <option value="{{ socr }}">{{ socr }}</option>
                    {% endfor %}
                </select>
                <input type="checkbox" class="street_polygon" value="1">
                <input class="object_filter" value="" />
                <input type="hidden" class="object_res" value="" />
            </div>
            <div>
                <input type="hidden" class="polygon-points" value="" />
                <input class="show_street" name="show_street" type="button" value="Показать Улицы!" />
            </div>
            <div class="street_res">
            </div>
        </div>
        <div class="map" style="position: fixed;width:{{ map_width }};height:{{ map_height }}"></div>
    </div>
</div>
{% endblock %}
{#
{% extends 'CommonBundle:Default/admin:admin_index.html.twig' %}

{% set admin = 'admin_address_group' %}
{% set title = 'label.address_group.index' %}
{% block thead %}
    <tr>
        <th>{{ 'label.id'|trans }}</th>
        <th>{{ 'label.name'|trans }}</th>
        <th>{{ 'label.actions'|trans }}</th>
    </tr>
{% endblock %}
{% block custom_fields %}
    <td>{{ entity }}</td>
{% endblock %}#}